// Naify

#pragma once

#include "NativeGameplayTags.h"

namespace GasBossGameplayTags
{
    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);

    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);

    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
    GASBOSS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Axe);
}
